#!/bin/sh
#PATH=$(cd "${0%/*}"; pwd):$PATH

usage()
{
	echo "Usage: $0 <[start]|restart|stop|pause|resume|redir|status>"
	echo
	echo "Remote Socks mode (ipt2socks only): $0 <HOST>[:PORT]"
	echo
	exit 0
}

redir()
{
	iptables -t nat $1 OUTPUT -p tcp -m set --match-set gfwlist dst -m owner ! --uid-owner wing -j REDIRECT --to-port 1088
	iptables -t nat $1 PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1088
}

start()
{
	# prepage
	[ -z $2 ] && usage

	# resolve
	if echo $2 | grep : > /dev/null; then
		HOST=`echo $2 | cut -d : -f 1`
		PORT=`echo $2 | cut -d : -f 2`
	else
		HOST=$2
		PORT=
	fi

	ulimit -n 65536

	# setup user for running wing
	if ! grep "wing" /etc/passwd > /dev/null; then
		echo 'wing:x:23333:23333::/var/empty:/bin/false' >> /etc/passwd
		echo 'wing:*:16000:0:99999:7:::' >> /etc/shadow
	fi

	# load owner extention for iptables
	modprobe xt_owner

	# trojan (deleted)
	if [ -z $3 ]; then
		[ -z $PORT ] && PORT=1080
		RUN_TYPE=socks
	fi

	# ipt2socks
	if [ $RUN_TYPE != nat ]; then
		IPT2SOCKS_CMD="ipt2socks -u wing -s $HOST -p $PORT -b 0.0.0.0 -l 1088 -T -4 -R -j `cat /proc/cpuinfo|grep processor|wc -l`"
		if [ $1 -ge 5 ]; then
			$IPT2SOCKS_CMD &
		elif [ $1 -ge 2 ]; then
			nohup $IPT2SOCKS_CMD &> /tmp/ipt2socks.log &
		else
			nohup $IPT2SOCKS_CMD -v &> /tmp/ipt2socks.log &
		fi
	fi

	# iptables
	ipset create gfwlist iphash
	ipset add gfwlist 8.8.8.8
	redir -A

	echo "Wing is running in $RUN_TYPE mode..."
}

stop()
{
	redir -D
	ipset destroy gfwlist
	[ -f /tmp/ipt2socks.log ] && rm /tmp/ipt2socks.log ; killall ipt2socks 2> /dev/null
}

status()
{
	[ ${1::4} = ipt2 ] && ([ -f /tmp/ipt2socks.log ] && tail -f /tmp/ipt2socks.log; return)

	([ -z $1 ] || [ ${1::3} = ipt ]) && iptables -t nat -L PREROUTING && iptables -t nat -L OUTPUT
	([ -z $1 ] || [ ${1::3} = ips ]) && echo && ipset -L gfwlist | more

	[ -z $1 ] && [ -f /tmp/ipt2socks.log ] && echo && cat /tmp/ipt2socks.log | more

	([ -z $1 ] || [ ${1::1} = d ]) && tail -f /tmp/syslog.log
}

case "$1" in
	start)
		start 2 $2 $3 $4 $5
		;;
	stop)
		stop
		;;
	restart)
		stop
		start 2 $2 $3 $4 $5
		;;
	pause)
		redir -D
		;;
	resume)
		ipset test gfwlist 8.8.8.8 && (redir -C || redir -A)
		;;
	redir)
		redir $2
		;;
	s|status)
		status $2
		;;
	-v0|-v1|-v2|-v3|-v4|-v5)
		start ${1:2} $2 $3 $4 $5
		;;
	-v)
		start 1 $2 $3 $4 $5
		;;
	*)
		start 5 $1 $2 $3 $4
		;;
esac


